# Generated by Django 3.0.6 on 2020-05-31 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.CharField(max_length=300),
        ),
    ]
